#!/usr/bin/env python3
#-*-coding:utf-8-*-
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2021 ImmortalWrt.org

import os, re, shutil

topdir = os.environ['PWD']
os.environ['TOPDIR'] = topdir

if os.access(topdir + '/logs/package/error.txt', os.F_OK):
	with os.popen('make --no-print-directory -C target/linux val.ARCH_PACKAGES') as command:
		pkgarch = command.read().strip()

		log_dir = '%s/tmp/buildbot_log/%s/' % (topdir, pkgarch)
		os.system('rm -rf ' + log_dir)

		with open(topdir + '/logs/package/error.txt', 'r') as file:
			for line in file.readlines():
				line = line.strip()

				log_path = line.split(' ')[1]
				if 'build variant' in line: log_path += '/' + line.split(' ')[7].replace(').', '')
				log_path_strip = re.sub('(^package/feeds/|^package/)', '', log_path)

				try:
					os.makedirs(log_dir + os.path.dirname(log_path_strip))
				except FileExistsError:
					# print('Skipping existing dir: "%s"' % log_dir + os.path.dirname(log_path_strip))
					pass
				except:
					print('Failed to create dir: "%s"' % log_dir + os.path.dirname(log_path_strip))
					exit(1)

				try:
					shutil.copytree('%s/logs/%s' % (topdir, log_path), log_dir + log_path_strip)
					print(line)
				except FileExistsError:
					# print('Skipping existing dir: "%s"' % log_dir + log_path_strip)
					pass
				except:
					print('Failed to create dir: "%s"' % log_dir + log_path_strip)
					exit(1)
