#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2021-2022 ImmortalWrt.org

export TOPDIR="$PWD"
BIN_DIR="$(make --no-print-directory -C target/linux val.BIN_DIR)"
KMOD_DIR="$(make --no-print-directory -C target/linux val.LINUX_VERSION val.LINUX_RELEASE val.LINUX_VERMAGIC | tr '\n' '-' | head -c -1)"

rm -rf "$BIN_DIR/kmods/$KMOD_DIR"
mkdir -p "$BIN_DIR/kmods/$KMOD_DIR"

cp -fpR "$BIN_DIR/packages"/automount* "$BIN_DIR/kmods/$KMOD_DIR"/
rsync --include="/kmod-*.ipk" --exclude="*" -av "$BIN_DIR/packages/" "$BIN_DIR/kmods/$KMOD_DIR/"

make package/index PACKAGE_SUBDIRS="$BIN_DIR/kmods/$KMOD_DIR" V=s
